### ISSUE TITLE
Support semver style versioning

### ISSUE THREAD

**Issue by JustinBeckwith** [google/closure-compiler-js#10]
Greetings!  Currently the version in package.json looks to be a date :)  

`20160822.0.0`

It would be great to use [semantic versioning](https://docs.npmjs.com/getting-started/semantic-versioning) so we can predict breaking changes, minor patches, etc.    @jmdobry and I went through a similar exercise with the [Google API Client for Node.js](https://github.com/google/google-api-nodejs-client/), so let us know if we can help!

**Comment by Dominator008** [comment]
Thanks. As you can see we use what I call "timever" where the string `20160822` can roughly be treated as the major version in semver. It is likely that every monthly release might introduce a small amount of backwards-incompatible change. For a complex optimizing compiler it is kind of hard to rule out the possibility of breaking changes :(

So yeah it's kind of a maintenance pain if you use NPM, but we do have a mostly predictable release cycle of one month.

**Comment by samthor** [comment]
This matches the [main repo](https://github.com/google/closure-compiler), so we're unlikely to change it.
