### ISSUE TITLE
Using with node module gulp-closure-compiler

### ISSUE THREAD

**Issue by Cinemacloud** [google/closure-compiler-js#103]
Curious if there's a way or version  of the above repo to make this work. I see the simple Gulp example here but our project seems to extensively use gulp-closure-compiler provided by java version of google-closure-compiler which doesn't have a simple way of converting it to js only. 

Thanks,
Peter

**Comment by ChadKillingsworth** [comment]
It will very soon: https://github.com/google/closure-compiler-npm/pull/81
