### ISSUE TITLE
Feature request: support strictCheckTypes

### ISSUE THREAD

**Issue by amarcu5** [google/closure-compiler-js#106]
Now that `--newTypeInf` is depreciated I think it would be a good time to support `strictCheckTypes` or better yet `--jscompError` flags

**Comment by leeoniya** [comment]
> Development has moved to the google-closure-compiler npm package at https://github.com/google/closure-compiler-npm.

this probably belongs in a prominent heading at the top of the main readme

**Comment by ChadKillingsworth** [comment]
Yeah I agree. cc @samthor
