### ISSUE TITLE
google-closure-compiler-js:command not found

### ISSUE THREAD

**Issue by LEggcookies** [google/closure-compiler-js#107]
Can't you install it from the command line now?
How to use google-closure-compiler-js on the new google-closure-compiler?

**Comment by brad4d** [comment]
The GitHub project you're looking for is
https://github.com/google/closure-compiler-npm

It defines all of the NPM packages for closure-compiler, including the one that is compiled to JS.
I believe you'll be able to get the answers you're looking for there.
If you don't find them, please file an issue on that project.
Thanks.
