### ISSUE TITLE
Webpack compilation error when code splitting

### ISSUE THREAD

**Issue by kruczy** [google/closure-compiler-js#15]
When using webpack code splitting the compiler will flag an error for missing `webpackJsonp` function:

```
asyncCommons.part.js:2 (JSC_UNDEFINED_VARIABLE)
variable webpackJsonp is undeclared
webpackJsonp([0],{
```

is there a way to tell the compiler that a global variable/function will be available on runtime?

Thanks

**Comment by Dominator008** [comment]
@kruczy What you need is an [externs file](https://developers.google.com/closure/compiler/docs/api-tutorial3) for Webpack. I don't remember seeing one off the top of my head though.

**Comment by samthor** [comment]
What is `webpackJsonp`? You may be able to add an externs file that looks like this-

```js
/** @externs */

/**
 * @param {!Array<number>} first
 * @param {!Object} second
 */
var webpackJsonp = function() {};
```

**Comment by kruczy** [comment]
`webpackJsonp` is a callback that is called from dynamically loaded chunks to declare all the modules so they can be imported

externs seems like the correct way to do this
Thanks alot
