### ISSUE TITLE
Instructions for running the closure-compiler in the browser

### ISSUE THREAD

**Issue by viebel** [google/closure-compiler-js#18]
Where are the instructions for running the closure-compiler in the browser?

**Comment by samthor** [comment]
Good call. We've not documented it well. For now, download the NPM published code-

```bash
$ npm install google-closure-compiler-js
```

Then pull out the 'jscomp.js' file. If you load it inside a browser, it'll add the global method `window.compile`.

That method then accepts flags as per the instructions in the main README. Does that work for you?

**Comment by viebel** [comment]
@samthor It works like a charm.
I've built a demo page of the closure compiler running in the browser using a tool of mine, named [KLIPSE](https://github.com/viebel/klipse).

Here is the demo page: http://viebel.github.io/klipse/examples/google_closure_compiler_advanced.html

I feel that this kind of demo pages will really help you guys to educate the community about the power of the closure compiler.

**Comment by samthor** [comment]
Thanks a lot! If you wanted to make that page faster or more responsive, I'd suggest offloading the compiler to a Web Worker so the page doesn't lock up during the compile.

**Comment by viebel** [comment]
Good idea!

Would you like to build demo pages or blog posts of your own (maybe using KLIPSE?)?
