### ISSUE TITLE
Dependency resolution

### ISSUE THREAD

**Issue by polkovnikov-ph** [google/closure-compiler-js#19]
Is a translation of [this folder](https://github.com/google/closure-library/tree/master/closure/bin/build) going to make its way into the project? I've [made a translation](https://github.com/polkovnikov-ph/closure-test/blob/master/build/closure.js#L242-L396) back in 2014, but it was one of the first projects in JS, and it's horrible.

**Comment by concavelenz** [comment]
Personally, I would love to ditch the Python for node tools.

**Comment by samthor** [comment]
I'm not 100% sure, nor have I seen that Python code before. I wonder if this is to do with the Closure [dependency/module stuff](http://stackoverflow.com/questions/10395810/how-do-i-split-my-javascript-into-modules-using-googles-closure-compiler/10401030#10401030).

@joeltine, looks like you were the last one to touch it?

**Comment by polkovnikov-ph** [comment]
@samthor That code is used to solve `goog.require`s and pass files into compiler in correct order (i.e. as a toposort of a DAG). I've tried compiling with `closure-compiler-js` two files A and B with A depending on B, and it didn't work for this reason.

**Comment by joeltine** [comment]
Echoing what @concavelenz said, I'd love to see those tools written in NodeJS. To be perfectly honest, it's probably low priority for the Closure Library team. I'd look at a PR if someone wanted to attempt adding them though.

**Comment by ChadKillingsworth** [comment]
Dependency management for multiple systems is now supported in the main build: Please switch to the main distribution at https://github.com/google/closure-compiler-npm
