### ISSUE TITLE
Flags should have a "defines" property

### ISSUE THREAD

**Issue by jeffpar** [google/closure-compiler-js#22]
The Java command-line interface supports any number of **--define** arguments that are useful for overriding [@define](https://github.com/google/closure-compiler/wiki/Annotating-JavaScript-for-the-Closure-Compiler#define-type-description) variable definitions.  I haven't seen any way to do the same thing in the JavaScript version of the compiler, so I've had to resort to [modifying my source code](https://github.com/jeffpar/pcjs/blob/next-release/gulpfile.js#L93) on the fly.  Apologies if I've overlooked something.

**Comment by samthor** [comment]
We've not implemented all the flags, as it's a manual process to bring them across to this entry point, and not all of them line up. This sounds like a great candidate, I'll make sure this is in the next release.

**Comment by samthor** [comment]
Also just to make two observations on that gulpfile-

* This compiler only accepts files that are in-memory (so you can't reference them on disk - we'd just load them fully anyway), re: `externs.js`
* `outputWrapper` wasn't implemented (we thought it was, and documented it as such). It's also coming next release.

**Comment by jeffpar** [comment]
Sounds good--thanks for the feedback.

**Comment by samthor** [comment]
This is released in [20160916](https://github.com/google/closure-compiler-js/releases/tag/20160916.0.0), here and on NPM.

**Comment by jeffpar** [comment]
Quick question: now that outputWrapper is implemented, does that obviate the need for assumeFunctionWrapper?  If not, does outputWrapper at least automatically default assumeFunctionWrapper to true, or at least enable the same optimizations that assumeFunctionWrapper enables, or are both still required?
