### ISSUE TITLE
Unhandled flags

### ISSUE THREAD

**Issue by tSte** [google/closure-compiler-js#29]
I just tried to switch from Java-based and hit a brick wall... I assumed that every flag should be provided as camelcase. So I rewrote my closure compiler config object and compiler complains about these flags:

`entry_point`=> `entryPoint`(pretty important flag to have)
`jscomp_Off`=> `jscompOff`
`extra_annotation_name`=> `extraAnnotationName`(very useful)
`manage_closure_dependencies`=> `manageClosureDependencies`
`debug`(very useful)

Could you please provide a way how to supply those flags?

**Comment by MatrixFrog** [comment]
Not all flags are available but @samthor is working on making more of them available.

**Comment by samthor** [comment]
Yup, the README states "some features are not available". The supported flags [are listed here](https://github.com/google/closure-compiler-js#flags).

Having said that, your requirements are on the list and will hopefully come soon.

**Comment by hiranpodi** [comment]
when the entry_point flag will be available ?

**Comment by samthor** [comment]
`extraAnnotationNames` is now supported (as an array).

**Comment by freshp86** [comment]
@danbeam, @MatrixFrog 

`polymerPass` flag is documented at https://github.com/google/closure-compiler-js#flags, but it is not actually supported. I get the following error when I pass it

```
Error: java.lang.RuntimeException: Unhandled flag: polymerPass
    at hJ.FG [as Tf] (/usr/local/google/home/dpapad/workspace/chromium1/src/third_party/node/node_modules/google-closure-compiler-js/jscomp.js:7660:22228)
    at hJ.IG [as Vf] (/usr/local/google/home/dpapad/workspace/chromium1/src/third_party/node/node_modules/google-closure-compiler-js/jscomp.js:7660:22429)
```

Trying to debug the minified `jscomp.js` code clearly shows that there is some global object somewhere that has a list of all flags that are consumed, and is *not* containing that flag, so it is left unconsumed and therefore throws the error, see related code below
![image](https://cloud.githubusercontent.com/assets/7547039/25686430/f27ae378-3022-11e7-814b-ddca4f736418.png)

**Comment by danbeam** [comment]
@freshp86 and I figured out the new equivalent is polymerVersion=1 and that polymerPass will like be restored (to mean polymerVersion=1) in newer versions
