### ISSUE TITLE
Can't get compiler to compile in dependencies.

### ISSUE THREAD

**Issue by bogusred** [google/closure-compiler-js#32]
I have source that is using google closure library. I'm using goog.provide and goog.require throughout my code.

I tried the gulp version of this compiler out today and was unsuccessful in getting this to work. It throws errors with the following compiler flags
continueWithWarnings
manageClosureDependencies
closureEntryPoint
onlyClosureDependencies

So I tried to comment them out. But the js it results with doesn't actually work and is incomplete. I could not figure out how to tell the compiler what the list of my dependencies is. In the interface for `gulp-closure-compiler`, you provide the full list of files when you call `gulp.src`. The resulting file name is defined in the compiler config object instead.

However with this compiler, i have to define the entry file to gulp.src instead of the full list of sources. If there is a way to define my full list of sources, I couldn't find it explained in the readme. 

Also I'm not able to specify the closure entry point. And it doesn't seem to read my `goog.require` statements to look for the dependencies and compile it together.

Here's the config i tried.

```
gulp.task('herc-docs:js', function() {
  return gulp.src('./site/docs/skins/hercules/assets/js/app.js', {base: './'})
      .pipe(closureCompiler({
    jsOutputFile: 'hercdocs.min.js',
    //continueWithWarnings: true,
    angularPass: true,
    exportLocalPropertyDefinitions: true,
    //closureEntryPoint: 'hercules.demo.app',
    compilationLevel: 'WHITESPACE_ONLY',
    createSourceMap: path.join('./', '/%outname%.map'),
    generateExports: true,
    outputWrapper: '(function(){%output%}).call(window);' +
        '\n//# sourceMappingURL=/releases/latest/' + fileName + '.map',
    //manageClosureDependencies: true,
    //onlyClosureDependencies: true,
    warningLevel: 'DEFAULT', // VERBOSE, QUIET
    languageIn: 'ECMASCRIPT6_STRICT',
    languageOut: 'ECMASCRIPT5',
    externs: [
      'node_modules/google-closure-compiler/contrib/externs/angular-1.5.js',
      'node_modules/google-closure-compiler/contrib/externs/angular-1.5-q_templated.js',
      'node_modules/google-closure-compiler/contrib/externs/angular-1.5-http-promise_templated.js',
      'node_modules/google-closure-compiler/contrib/externs/angular-1.5-resource.js',
      'site/docs/skins/hercules/assets/js/externs.js'
    ]
  }))
      .pipe(gulp.dest('site/docs/skins/hercules/assets/js'));
});
```

For reference, here's what it looks like with `gulp-closure-compiler`

```
gulp.task('herc-docs:js', function() {
  return gulp.src(['foo.js', 'bar.js', 'bat.js'])
      .pipe(closureCompiler({
        fileName: 'main.min.js',
        compilerFlags: {...}
      }))
      .pipe(gulp.dest('site/docs/skins/hercules/assets/js'));
});
```

**Comment by 2pha** [comment]
Did you ever figure this out? I'm in the same boat.

**Comment by ChadKillingsworth** [comment]
Please switch to the main distribution at https://github.com/google/closure-compiler-npm

**Comment by bogusred** [comment]
This is a pretty old issue and don't remember. totally ok to just close this one out. Thanks for taking a look.
