### ISSUE TITLE
Externs for node.js core modules; documentation unclear?

### ISSUE THREAD

**Issue by benjaminjt** [google/closure-compiler-js#33]
It isn't clear how to reference externs.

For example, having trouble with node core modules. Using the gulp plugin to attempt to compile a Node application which includes the following:

``` js
const http = require('http');
```

I get the following errors:

```
[00:45:29] source/Stats.js:2 (JSC_COMMONJS_MODULE_LOAD_ERROR)
[00:45:29] Failed to load module "http"
[00:45:29] const http = require('http');
```

Despite including the following flags:

``` js
processCommonJsModules: true,
externs: [{ path: './externs/http.js' }],
```

Where `./externs/http.js` is from https://github.com/dcodeIO/node.js-closure-compiler-externs

Surely compiling a node app with core modules is a common use case. Could we include a brief example, or perhaps just an indicator of how to use common externs?

I would offer to contribute, but I really have no idea how to get this working...

Cheers!

**Comment by brad4d** [comment]
I've been tinkering a bit with using closure-compiler to check for errors in code intended for Node.js. Here's an example command line. Note that I have to disable the errors related to module loading.

```sh
find . -name '*.js' -print \
    | xargs closure-compiler  \
        --process_common_js_modules \
        --jscomp_off=commonJsModuleLoad \
        --jscomp_error=checkTypes \
        --checks_only
```

What works:
-   Any types you've defined correctly in your own code will be correctly checked by the compiler.
-   Other compiler checks will also run to warn you of possible errors in your code.

What doesn't:
-   The closure-compiler doesn't yet know how to handle imports for native Node.js stuff. With the module loading error suppressed, all of the stuff imported this way will be treated as unknown `{?}` type.
-   There's an outstanding pull request I'm reviewing to make closure-compiler understand how to find code in node_modules directories and using info from `package.json` files. https://github.com/google/closure-compiler/pull/2094

**Comment by Ch4s3** [comment]
Did this get merged?

**Comment by ChadKillingsworth** [comment]
We don't have a good story for compiling NodeJS code with closure compiler currently.
