### ISSUE TITLE
Rollup Compatibility

### ISSUE THREAD

**Issue by kennetpostigo** [google/closure-compiler-js#38]
Would there be anyway you could add compatibility for `rollup` similarly to what you have for webpack? I use rollup currently to build my library and It would be awesome to use closure compiler to minimize the size of it libs.

**Comment by kylecordes** [comment]
There is a NPM package already out there that does this:

https://www.npmjs.com/package/rollup-plugin-closure-compiler-js

Unfortunately it is a couple of months behind in the version of closure-compiler-js it uses; providing this (quite simple, a couple of small source files) functionality in the closure-compiler-js box would be very helpful and always up-to-date.

If a project committer gives a green light that such a feature is desirable and that PR would likely be accepted, I might jump in and create the PR.
