### ISSUE TITLE
Externs for angular-1.5.js doesn't work

### ISSUE THREAD

**Issue by Tobino** [google/closure-compiler-js#46]
I'm currently trying to compile an angular project with closure with gulp

.pipe(compiler({
	compilationLevel: 'ADVANCED',
	externs:[
		{ path: './externs/angular-1.5.js' }
	],
	jsOutputFile: 'app.js'
}))

By it doesn't affect the result. I have still result as angular.b instead of angular.module with no error on compile.
 How to load externs ?

**Comment by ChadKillingsworth** [comment]
I realize this is very old, but the JS version now can just take a file path for the `externs` flag and will load the externs from the filesystem (when running in NodeJS).
