### ISSUE TITLE
Support for extraAnnotationNames

### ISSUE THREAD

**Issue by tschaub** [google/closure-compiler-js#48]
It looks to me like there is not a flag that provides the equivalent of `--extra_annotation_name`.  I see `extaAnnotationNames` in the `jscomp.js` build, but get an error when trying to use it.

Would it be possible to suppress warnings about specific unrecognized annotations?

**Comment by Dominator008** [comment]
This is being added.

**Comment by Dominator008** [comment]
Closed by https://github.com/google/closure-compiler/commit/553661cb69073087abc063e630119c88a6388552
