### ISSUE TITLE
node.js + closurecompiler.js

### ISSUE THREAD

**Issue by aslushnikov** [google/closure-compiler-js#60]
I'm trying to use closurecompiler.js to lint types in node.js application. However, closure fails to resolve global modules  – e.g. `require("fs")` fails.

Is this supported? What's the workaround for this? I would appreciate any guidance and examples.

Here is a demo repository which exhibits the problem: [example-node-types](https://github.com/aslushnikov/example-node-types)

**Comment by samthor** [comment]
dup of #33.
