### ISSUE TITLE
Not compatible with node.js v4

### ISSUE THREAD

**Issue by yeyingxian** [google/closure-compiler-js#65]
I am using ubuntu 16.04, and node.js was installed by apt-get. The version of node.js for ubuntu 16.04 is 4.2.6. When installed google-closure-compiler-js with npm, the command is not runing. The error is

root@ubuntu:/home/licode/erizoAPI# google-closure-compiler-js 
/usr/local/lib/node_modules/google-closure-compiler-js/cmd.js:58
Promise.all([sources, externs]).then(arr => ready(...arr)).catch(error);
                                                  ^^^

SyntaxError: Unexpected token ...
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:374:25)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Function.Module.runMain (module.js:442:10)
    at startup (node.js:136:18)
    at node.js:966:3

I think node.js v4 doesn't support some kinds of arrow function

**Comment by MatrixFrog** [comment]
https://github.com/google/closure-compiler-js/blob/master/cmd.js#L58

We can change this to ready.apply(arr) or we can just say we don't support node 4. I will leave that up to @samthor I guess.

**Comment by graham-h** [comment]
@yeyingxian this works for me now on 4.8.7, so hopefully works for you too.
