### ISSUE TITLE
Error: Process spawn error. Is java in the path?

### ISSUE THREAD

**Issue by nazar-pc** [google/closure-compiler-js#67]
Node 8.1.3, closure-compiler-js fails with:
```
events.js:182
      throw er; // Unhandled 'error' event
      ^
Error: Process spawn error. Is java in the path?
spawn java ENOENT
```

Can be reproduced with:
```
git clone https://github.com/webcomponents/shadycss.git
npm install
npm run build
```

And yes, I do not have Java installed and do not plan to install.

**Comment by samthor** [comment]
ShadyCSS depends on the [Java version](https://github.com/google/closure-compiler) of the compiler. Please file an issue on ShadyCSS.
