### ISSUE TITLE
"<>=&" is compiled to "\x3c\x3e\x3d\x26"

### ISSUE THREAD

**Issue by leeoniya** [google/closure-compiler-js#79]
probably missing some other entities here, too. this does not happen in the Java version.

test code:

```js
const closure = require('google-closure-compiler-js').compile;

var test = 'var x = "<>=&";';

const flags = {
  jsCode: [{src: test}],
  languageIn: 'ECMASCRIPT5_STRICT',
  languageOut: 'ECMASCRIPT5',
  compilationLevel: 'SIMPLE',
};

var compiled = closure(flags).compiledCode;

console.log(compiled);       // var x="\x3c\x3e\x3d\x26";
```

**Comment by MatrixFrog** [comment]
IIRC this is the "trustedStrings" option. https://github.com/google/closure-compiler/blob/master/src/com/google/javascript/jscomp/CompilerOptions.java#L988

We can probably turn it on by default for the JS version.

**Comment by leeoniya** [comment]
hmm, thanks. i'll try that.

FWIW the java version did also escape angle brackets but only if they were part of an html comment in a string: `"<!-- foo -->"` -> `"\x3c!-- foo --\x3e"`. i dont believe this is technically necessary either. (unlike escaping `/` in `"</script>"`.

**Comment by ChadKillingsworth** [comment]
The trusted strings option is now set. Deployment has moved to https://github.com/google/closure-compiler-npm

**Comment by leeoniya** [comment]
sorry, misunderstood. thanks.
