### ISSUE TITLE
Closure Compiler for use in the browser without webpack or grunt

### ISSUE THREAD

**Issue by tomgallagher** [google/closure-compiler-js#81]
Hi

Is it possible to use Closure Compiler in the browser, for example in a Chrome Extension, without using Node, let alone webpack or grunt? Can it be used as a standalone JS library?

If so, where can I find the js file?

Thanks

**Comment by MatrixFrog** [comment]
We have a demo at https://closure-compiler-debugger.appspot.com/gwt_debugger.html as well as npmjs.com/package/google-closure-compiler-js but it's not as well supported as the Java version at this time.

**Comment by tomgallagher** [comment]
Thanks for getting back  I'll take a look.


Sent from Samsung Mobile on O2
-------- Original message --------From: Tyler Breisacher <notifications@github.com> Date: 03/11/2017  17:07  (GMT+00:00) To: google/closure-compiler-js <closure-compiler-js@noreply.github.com> Cc: Pathfinder <thomasgallagher101@gmail.com>, Author <author@noreply.github.com> Subject: Re: [google/closure-compiler-js] Closure Compiler for use in the browser without webpack or grunt (#81) 
We have a demo at https://closure-compiler-debugger.appspot.com/gwt_debugger.html as well as npmjs.com/package/google-closure-compiler-js but it's not as well supported as the Java version at this time.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/google/closure-compiler-js","title":"google/closure-compiler-js","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/google/closure-compiler-js"}},"updates":{"snippets":[{"icon":"PERSON","message":"@MatrixFrog in #81: We have a demo at https://closure-compiler-debugger.appspot.com/gwt_debugger.html as well as npmjs.com/package/google-closure-compiler-js but it's not as well supported as the Java version at this time."}],"action":{"name":"View Issue","url":"https://github.com/google/closure-compiler-js/issues/81#issuecomment-341767195"}}}
