### ISSUE TITLE
passing --defines on command line 

### ISSUE THREAD

**Issue by reshadi** [google/closure-compiler-js#90]
Hello,
The 'defines' flag expects an object, but I could not figure out how to pass an object on the command line.
The java version accepts multiple --define "name=value" on the CLI.
The js version is using minimist and I could find any code that converts cli arguments to an object. If I pass multiple, it turns them into an array, not an object that is expected.
Is there a way to do this from cli? 

If not, I can contribute the code.

Thanks.

**Comment by samthor** [comment]
The CLI version of the -js compiler was contributed. It's likely that it doesn't support the same syntax as the Java version, and we'd be happy for you to contribute it.

**Comment by reshadi** [comment]
Ok, sent the pull request.
thanks.

**Comment by reshadi** [comment]
Hello, this pull request has been merged, any idea when the next release will be? 
thanks.

**Comment by ChadKillingsworth** [comment]
It's release everytime the main compiler is released.
