### ISSUE TITLE
Add lumo in the Build systems section 

### ISSUE THREAD

**Issue by arichiardi** [google/closure-compiler-js#92]
Hello folks,

The Clojure community as you probably well know is very keen on the Google Clojure Compiler on the JVM. Some folks like @anmonteiro and myself are very keen on this port because it allows us to work with no JVM whatsoever.
Antonio created [lumo](https://github.com/anmonteiro/lumo) for exactly this purpose and I was wondering whether we can add it to the Build system section here in the README.

This might be a little bit of a stretch so in case it is not appropriate we can list it in a transpilers section or something.

In any case, thank you for working on it!

**Comment by ChadKillingsworth** [comment]
If you want to PR a change to the docs at https://github.com/google/closure-compiler-npm, I'll review it and get it merged.

This repo is being sunset.
