### ISSUE TITLE
Gulp: doesn't work with empty streams

### ISSUE THREAD

**Issue by fabiospampinato** [google/closure-compiler-js#99]
If the stream is empty, i.e. doesn't contain any files, after running this plugin I have one file named `compiled.js` in the stream with this as content: `'use strict';`

This plugin shouldn't add any files to an empty stream.

**Comment by ChadKillingsworth** [comment]
This is fixed by https://github.com/google/closure-compiler-npm/pull/81

**Comment by fabiospampinato** [comment]
@ChadKillingsworth great! I'll close this as soon as there's a version of `google-closure-compiler-js` pushed to NPM that fixes this, which I don't think it's the case atm, right?

**Comment by ChadKillingsworth** [comment]
Correct - but I wish to point out that you'll be switching packages. There will only be a `google-closure-compiler`.

**Comment by fabiospampinato** [comment]
All right, I'll just switch to `google-closure-compiler` then, thank you.

**Comment by ChadKillingsworth** [comment]
It was published today.
